//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSPackage.CPPCheckPlugin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>C:\Program Files (x86)\Cppcheck\cppcheck.exe</string>
  <string>C:\Program Files\Cppcheck\cppcheck.exe</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection CPPcheckPath {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["CPPcheckPath"]));
            }
            set {
                this["CPPcheckPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InconclusiveChecksEnabled {
            get {
                return ((bool)(this["InconclusiveChecksEnabled"]));
            }
            set {
                this["InconclusiveChecksEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultArguments {
            get {
                return ((string)(this["DefaultArguments"]));
            }
            set {
                this["DefaultArguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProjectOnlyCheckCurrentConfig {
            get {
                return ((bool)(this["ProjectOnlyCheckCurrentConfig"]));
            }
            set {
                this["ProjectOnlyCheckCurrentConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileOnlyCheckCurrentConfig {
            get {
                return ((bool)(this["FileOnlyCheckCurrentConfig"]));
            }
            set {
                this["FileOnlyCheckCurrentConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("style,information,warning,performance,portability")]
        public string SeveritiesString {
            get {
                return ((string)(this["SeveritiesString"]));
            }
            set {
                this["SeveritiesString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("unmatchedSuppression")]
        public string SuppressionsString {
            get {
                return ((string)(this["SuppressionsString"]));
            }
            set {
                this["SuppressionsString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool CheckSavedFiles {
            get {
                return ((bool)(this["CheckSavedFiles"]));
            }
            set {
                this["CheckSavedFiles"] = value;
            }
        }
    }
}
